$:
  vscode:
    - services:
        - docker
      docker:
        build: 
          dockerfile: .ide/Dockerfile
  push:
    - runner:
        tags: cnb:arch:amd64
      services:
        - docker
      imports: https://cnb.cool/btpanel/secret/-/blob/main/docker.yml
      env:
        IMAGE_TAG: btpanel/baota:lamp_debian11-linux-amd64
      stages:
        - name: docker login
          script: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWD"
        - name: docker build
          script: docker build -t ${IMAGE_TAG} .
        - name: docker push
          script: docker push ${IMAGE_TAG}
        - name: resolve
          type: cnb:resolve
          options:
            key: build-amd64 
          
    - runner:
        tags: cnb:arch:arm64:v8
        cpus: 16
      services:
        - docker
      imports: https://cnb.cool/btpanel/secret/-/blob/main/docker.yml
      env:
        IMAGE_TAG: btpanel/baota:lamp_debian11-linux-arm64
      stages:
        - name: docker login
          script: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWD"
        - name: docker build
          timeout: 3600s
          script: docker build -t ${IMAGE_TAG} .
        - name: docker push
          script: docker push ${IMAGE_TAG}
        - name: resolve
          type: cnb:resolve
          options:
            key: build-arm64

    - services:
        - docker
      imports: https://cnb.cool/btpanel/secret/-/blob/main/docker.yml
      env:
        IMAGE_TAG: btpanel/baota:lamp_debian11
      stages:
        - name: await the amd64
          type: cnb:await
          options:
            key: build-amd64
        - name: await the arm64
          type: cnb:await
          options:
            key: build-arm64
        - name: manifest
          image: cnbcool/manifest
          settings:
            username: $DOCKER_USERNAME
            password: $DOCKER_PASSWD
            target: ${IMAGE_TAG}
            template: ${IMAGE_TAG}-OS-ARCH
            platforms:
              - linux/amd64
              - linux/arm64