name: Docker Multi-Arch Build and Push

on:
  workflow_dispatch:
    inputs:
      version:
        description: '宝塔版本'
        required: false
        default: '9.5.0'

jobs:
  build-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: lnmp

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set version variable
        id: vars
        run: echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT

      - name: Build and push amd64 image
        run: |
          docker buildx build --file ./Dockerfile --platform linux/amd64 \
            --tag ldxw/btpanel:${{ steps.vars.outputs.VERSION }}-amd64 \
            --tag ldxw/btpanel:latest-amd64 \
            --push .

  build-arm64:
    runs-on: ubuntu-latest
    needs: build-amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: lnmp

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set version variable
        id: vars
        run: echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT

      - name: Build and push arm64 image
        run: |
          docker buildx build --file ./arm64/Dockerfile --platform linux/arm64 \
            --tag ldxw/btpanel:${{ steps.vars.outputs.VERSION }}-arm64 \
            --tag ldxw/btpanel:latest-arm64 \
            --push .

  create-and-push-manifest:
    runs-on: ubuntu-latest
    needs: [build-amd64, build-arm64]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set version variable
        id: vars
        run: echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT

      - name: Create manifest
        run: |
          docker manifest create ldxw/btpanel:${{ steps.vars.outputs.VERSION }} \
            ldxw/btpanel:${{ steps.vars.outputs.VERSION }}-amd64 \
            ldxw/btpanel:${{ steps.vars.outputs.VERSION }}-arm64
          docker manifest create ldxw/btpanel:latest \
            ldxw/btpanel:latest-amd64 \
            ldxw/btpanel:latest-arm64

      - name: Annotate manifest
        run: |
          docker manifest annotate ldxw/btpanel:${{ steps.vars.outputs.VERSION }} \
            ldxw/btpanel:${{ steps.vars.outputs.VERSION }}-arm64 --os linux --arch arm64
          docker manifest annotate ldxw/btpanel:latest \
            ldxw/btpanel:latest-arm64 --os linux --arch arm64

      - name: Push manifest
        run: |
          docker manifest push ldxw/btpanel:${{ steps.vars.outputs.VERSION }}
          docker manifest push ldxw/btpanel:latest
    