name: Docker Multi-Arch Build and Push

on:
  workflow_dispatch:
    inputs:
      version:
        description: '宝塔版本号'
        required: false
        default: '9.5.0'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: lnmp
          
      - name: Check Dockerfile existence
        run: |
          if [ ! -f "./Dockerfile" ]; then
            echo "Root Dockerfile not found!"
            exit 1
          fi
          if [ ! -f "./arm64/Dockerfile" ]; then
            echo "ARM64 Dockerfile not found!"
            exit 1
          fi

      - name: Print directory structure
        run: |
          ls -R

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set version variable
        id: vars
        run: echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT

      - name: Build and push Docker images
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ldxw/btpanel:latest
            ldxw/btpanel:${{ steps.vars.outputs.VERSION }}
          file: |
            linux/amd64: ./Dockerfile
            linux/arm64: ./arm64/Dockerfile
    